//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExamen_8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        private static DataBaseEntities _context;
        public static DataBaseEntities GetContext()
        {
            if (_context == null)
                _context = new DataBaseEntities();
            return _context;
        }
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EdiniciIzmereniya> EdiniciIzmereniya { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Roli> Roli { get; set; }
        public virtual DbSet<Specifikacion> Specifikacion { get; set; }
        public virtual DbSet<Specifikacion_Material> Specifikacion_Material { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zakazchik> Zakazchik { get; set; }
    }
}
