//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExamen_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        public int Id_Polzovatelya { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Polzovatel_Roli { get; set; }
        public int Popitki_Vhoda { get; set; }
        public bool Blocked { get; set; }
    
        public virtual Roli Roli { get; set; }
    }
}
