//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExamen_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifikacion_Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specifikacion_Material()
        {
            this.Specifikacion = new HashSet<Specifikacion>();
        }
    
        public int Id_SpecifikacionMaterial { get; set; }
        public int SpecifikacionMaterial { get; set; }
        public int EdIzm { get; set; }
        public int Kolvo { get; set; }
    
        public virtual EdiniciIzmereniya EdiniciIzmereniya { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifikacion> Specifikacion { get; set; }
    }
}
