//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExamen_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifikacion
    {
        public int Id_Specifikacion { get; set; }
        public int Izgotovitel { get; set; }
        public int Specifikacion_Product { get; set; }
        public int Kolvo { get; set; }
        public int Material_Specifikacion { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Specifikacion_Material Specifikacion_Material { get; set; }
        public virtual Zakazchik Zakazchik { get; set; }
    }
}
