//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExamen_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazchik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakazchik()
        {
            this.Specifikacion = new HashSet<Specifikacion>();
        }
    
        public int Id_Zakazchik { get; set; }
        public string Name_Zakazchik { get; set; }
        public Nullable<decimal> Inn { get; set; }
        public string Addres { get; set; }
        public string Telephone { get; set; }
        public bool Salesman { get; set; }
        public bool Buyer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifikacion> Specifikacion { get; set; }
    }
}
